//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_StockTypes
    {
        public TLADM_StockTypes()
        {
            this.TLADM_NonStockItems = new HashSet<TLADM_NonStockItems>();
        }
    
        public int ST_Id { get; set; }
        public string ST_ShortCode { get; set; }
        public string ST_Description { get; set; }
    
        public virtual ICollection<TLADM_NonStockItems> TLADM_NonStockItems { get; set; }
    }
}
