//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_ConsumablesDC
    {
        public int ConsDC_Pk { get; set; }
        public string ConsDC_Code { get; set; }
        public string ConsDC_Description { get; set; }
        public int ConsDC_UOM_Fk { get; set; }
        public int ConsDC_AUOM_FK { get; set; }
        public decimal ConsDC_ConsFactors { get; set; }
        public int ConsDC_StockType_FK { get; set; }
        public bool ConsDC_Hazardous { get; set; }
        public bool ConsDC_ShowQty { get; set; }
        public bool ConsDC_ShowStdCost { get; set; }
        public int ConsDC_ReOrderLevel { get; set; }
        public int ConsDC_Economic_ReOrderQty { get; set; }
        public int ConsDC_MinReorderQty { get; set; }
        public int ConsDC_DelLeadTime { get; set; }
        public int ConsDC_StockTake_FK { get; set; }
        public decimal ConsDC_StandardCost { get; set; }
        public int ConsDC_Units { get; set; }
        public int ConsDC_PreferedSupplier_FK { get; set; }
        public bool ConsDC_Consignment { get; set; }
        public string ConsDC_Notes { get; set; }
        public string ConsDC_HazChem { get; set; }
        public int ConsDC_SizeCode_FK { get; set; }
        public int ConsDC_StoreCode_FK { get; set; }
        public int ConsDC_ConsGroup_FK { get; set; }
    }
}
