//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_ConsumableGroups
    {
        public TLADM_ConsumableGroups()
        {
            this.TLADM_ConsumablesOther = new HashSet<TLADM_ConsumablesOther>();
        }
    
        public int ConG_Pk { get; set; }
        public string ConG_ShortCode { get; set; }
        public string ConG_Description { get; set; }
    
        public virtual ICollection<TLADM_ConsumablesOther> TLADM_ConsumablesOther { get; set; }
    }
}
