//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_ProductRating_Detail
    {
        public int prd_Id { get; set; }
        public int prd_Parent_FK { get; set; }
        public int Prd_Weight { get; set; }
        public int Prd_Width { get; set; }
        public decimal Prd_Yield { get; set; }
        public decimal Prd_PiecesKg { get; set; }
    
        public virtual TLADM_FabWidth TLADM_FabWidth { get; set; }
    }
}
