//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLFIN_Calendar
    {
        public int Cal_Id { get; set; }
        public System.DateTime Cal_DateFrom { get; set; }
        public System.DateTime Cal_DateTo { get; set; }
        public int Cal_FinPeriod { get; set; }
        public string Cal_FinPeriod_Description { get; set; }
        public int Cal_Qtr { get; set; }
        public int Cal_Financial_Year_FK { get; set; }
    }
}
