//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    
    public partial class GreigeProduced_Result2
    {
        public int KnitO_Product_FK { get; set; }
        public string GreigeP_Grade { get; set; }
        public Nullable<int> Cnt { get; set; }
    }
}
