//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_BoxTypes
    {
        public int TLADMBT_Pk { get; set; }
        public string TLADMBT_ShortCode { get; set; }
        public string TLADMBT_Description { get; set; }
        public decimal TLADMBT_DryWeight { get; set; }
    }
}
