//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_Trims
    {
        public int TR_Id { get; set; }
        public string TR_Description { get; set; }
        public int TR_powerN { get; set; }
        public Nullable<bool> TR_Discontinued { get; set; }
        public Nullable<System.DateTime> TR_Discontinued_Date { get; set; }
        public bool Tr_Body { get; set; }
        public int TR_Weight { get; set; }
        public int TR_Width { get; set; }
        public Nullable<int> TR_Greige_FK { get; set; }
        public bool TR_IsBinding { get; set; }
        public Nullable<int> TR_Size_FK { get; set; }
        public bool TR_IsSizes { get; set; }
    }
}
