//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_StoreBal
    {
        public int StoreBal_Pk { get; set; }
        public int StoreBal_StoreId_FK { get; set; }
        public int StoreBal_Month { get; set; }
        public int StoreBal_Year { get; set; }
        public int StoreBal_FinishedGoods_FK { get; set; }
        public int StoreBal_NumberOf { get; set; }
        public Nullable<decimal> StoreBal_Weight { get; set; }
    }
}
