//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_PanelAttributes
    {
        public int Pan_PK { get; set; }
        public string Pan_Description { get; set; }
        public Nullable<bool> Pan_Discontinued { get; set; }
        public Nullable<System.DateTime> Pan_Discontinued_Date { get; set; }
        public int Pan_PowerN { get; set; }
        public string Pan_Grade { get; set; }
        public int Pan_Size_FK { get; set; }
        public bool Pan_Blocked { get; set; }
        public int Pan_UOM_FK { get; set; }
        public int Pan_PreferedSupplier_FK { get; set; }
        public bool Pan_ShowQty { get; set; }
        public int Pan_FabricAtributes_FK { get; set; }
    }
}
