//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_GreigeQuality
    {
        public int GQ_Pk { get; set; }
        public string GQ_Description { get; set; }
        public Nullable<bool> GQ_Discontinued { get; set; }
        public Nullable<System.DateTime> GQ_Discontinued_Date { get; set; }
        public int GQ_PowerN { get; set; }
    }
}
