//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_StylesAdditional
    {
        public int AddSty_Pk { get; set; }
        public int AddSty_Style_FK { get; set; }
        public int AddSty_Size_FK { get; set; }
        public int AddSty_Colour_FK { get; set; }
        public decimal AddSty_StandardCost { get; set; }
        public decimal AddSty_RefundCost { get; set; }
    }
}
