//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_StockTakeFreq
    {
        public int STF_Pk { get; set; }
        public string STF_ShortCode { get; set; }
        public string STF_Description { get; set; }
        public int STF_Period_Weeks { get; set; }
    }
}
