//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_FabricAttributes
    {
        public int FbAtrib_Pk { get; set; }
        public string FbAtrib_Description { get; set; }
        public int FbAtrib_Brand_FK { get; set; }
        public int FbAtrib_Greige_FK { get; set; }
        public int FbAtrib_Colour_FK { get; set; }
        public int FbAtrib_FabProduct_FK { get; set; }
        public int FbAtrib_FabProductTypes_FK { get; set; }
        public bool FbAtrib_Blocked { get; set; }
        public int FbAtrib_UOM_Fk { get; set; }
        public int FbAtrib_PreferedSupplier_FK { get; set; }
        public bool FbAtrib_BarCode { get; set; }
        public bool FbAtrib_ShowQty { get; set; }
        public Nullable<bool> FbAtrib_Discontinued { get; set; }
        public Nullable<System.DateTime> FbAtrib_Discontinued_Date { get; set; }
        public int FbAtrib_PowerN { get; set; }
    }
}
