//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_CompanyDetails
    {
        public int Comp_Pk { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Address { get; set; }
        public string Comp_TelephoneNo { get; set; }
        public string Comp_FaxNo { get; set; }
        public string Comp_ContactPerson { get; set; }
        public string Comp_ContactPersonEmail { get; set; }
        public int Comp_TotalPowerN { get; set; }
    }
}
