//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_Sizes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TLADM_Sizes()
        {
            this.TLADM_ConsumablesOther = new HashSet<TLADM_ConsumablesOther>();
        }
    
        public int SI_id { get; set; }
        public string SI_Description { get; set; }
        public int SI_PowerN { get; set; }
        public bool SI_Discontinued { get; set; }
        public Nullable<System.DateTime> SI_Discontinued_Date { get; set; }
        public string SI_FinishedCode { get; set; }
        public int SI_ColNumber { get; set; }
        public int SI_PastelNo { get; set; }
        public int SI_DisplayOrder { get; set; }
        public bool SI_Adult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TLADM_ConsumablesOther> TLADM_ConsumablesOther { get; set; }
    }
}
