//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_MachineMaintenanceTasks
    {
        public int TLMtask_Pk { get; set; }
        public int TLMtask_Dept_FK { get; set; }
        public string TLMtask_Description { get; set; }
    }
}
