//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_Colours
    {
        public int Col_Id { get; set; }
        public string Col_Description { get; set; }
        public int Col_PowerN { get; set; }
        public Nullable<bool> Col_Discontinued { get; set; }
        public Nullable<System.DateTime> Col_Discontinued_Date { get; set; }
        public string Col_FinishedCode { get; set; }
        public bool Col_HasAuxColors { get; set; }
        public int Col_AuxPowerN { get; set; }
        public string Col_Display { get; set; }
        public decimal Col_StandardTime { get; set; }
        public bool Col_Benchmark { get; set; }
        public bool Col_Added_InSession { get; set; }
        public bool Col_Removed_InSession { get; set; }
    }
}
