//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_StyleColour
    {
        public int STYCOL_Pk { get; set; }
        public int STYCOL_Style_FK { get; set; }
        public Nullable<int> STYCOL_Colour_FK { get; set; }
    }
}
