//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLADM_StoreTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TLADM_StoreTypes()
        {
            this.TLADM_ConsumablesOther = new HashSet<TLADM_ConsumablesOther>();
        }
    
        public int StoreT_Id { get; set; }
        public string StoreT_ShortCode { get; set; }
        public string StoreT_Description { get; set; }
        public int StoreT_UOMFK { get; set; }
        public int StoreT_ProdTypeFK { get; set; }
        public bool StoreT_Hazardous { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TLADM_ConsumablesOther> TLADM_ConsumablesOther { get; set; }
    }
}
