//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLCMT_LineFeederBundleCheck
    {
        public int TLCMTLF_Pk { get; set; }
        public int TLCMTLF_Operator_FK { get; set; }
        public int TLCMTLF_LineNo_FK { get; set; }
        public int TLCMTLF_CutSheet_FK { get; set; }
        public int TLCMTLF_Facility_FK { get; set; }
        public int TLCMTLF_Colour_FK { get; set; }
        public string TLCMTLF_Bundle_No { get; set; }
        public int TLCMTLF_Body_Qty { get; set; }
        public int TLCMTLF_Sleeve_Qty { get; set; }
        public int TLCMTLF_Labels_Qty { get; set; }
        public int TLCMTLF_Size_FK { get; set; }
        public int TLCMTLF_Difference { get; set; }
        public System.DateTime TLCMTFL_TransDate { get; set; }
        public string TLCMTFL_Comments { get; set; }
    }
}
