//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLCMT_CompletedWork
    {
        public int TLCMTWC_Pk { get; set; }
        public int TLCMTWC_PanelIssue_FK { get; set; }
        public System.DateTime TLCMTWC_TransactionDate { get; set; }
        public int TLCMTWC_LineIssue_FK { get; set; }
        public int TLCMTWC_ToWhse_FK { get; set; }
        public string TLCMTWC_BoxNumber { get; set; }
        public string TLCMTWC_PastelNumber { get; set; }
        public int TLCMTWC_Size_FK { get; set; }
        public string TLCMTWC_Grade { get; set; }
        public int TLCMTWC_Qty { get; set; }
        public decimal TLCMTWC_Weight { get; set; }
        public int TLCMTWC_CutSheet_FK { get; set; }
        public bool TLCMTWC_Despatched { get; set; }
        public Nullable<int> TLCMTWC_DepatchedList_FK { get; set; }
        public int TLCMTWC_Style_FK { get; set; }
        public int TLCMTWC_Colour_FK { get; set; }
        public int TLCMTWC_CMTFacility_FK { get; set; }
        public bool TLCMTWC_Picked { get; set; }
        public Nullable<int> TLCMTWC_PickList_FK { get; set; }
        public int TLCMTWC_BoxType_FK { get; set; }
        public bool TLCMTWC_BoxReceiptedWhse { get; set; }
        public bool TLCMTWC_CMTBilled { get; set; }
        public bool TLCMTWC_Is_A { get; set; }
        public bool TLCMTWC_MarkedForDeletion { get; set; }
    }
}
