//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLDYE_DyeTransactions
    {
        public int TLDYET_Pk { get; set; }
        public System.DateTime TLDYET_Date { get; set; }
        public Nullable<System.DateTime> TLDYET_RejectDate { get; set; }
        public string TLDYET_BatchNo { get; set; }
        public int TLDYET_SequenceNo { get; set; }
        public string TLDYET_TransactionNumber { get; set; }
        public int TLDYET_TransactionType { get; set; }
        public decimal TLDYET_BatchWeight { get; set; }
        public decimal TLDYET_TransactionWeight { get; set; }
        public string TLDYET_AuthorisedBy { get; set; }
        public int TLDYET_Batch_FK { get; set; }
        public Nullable<int> TLDYET_Customer_FK { get; set; }
        public int TLDYET_CurrentStore_FK { get; set; }
        public string TLDYET_Adjustment_Reasons { get; set; }
        public int TLDYET_Stage { get; set; }
        public bool TLDYET_Rejected { get; set; }
        public Nullable<bool> TLDYET_WriteOff { get; set; }
        public bool TLDYET_FabricSales { get; set; }
        public string TLDYET_CustomerOrderNo { get; set; }
        public int TLDYET_MeasurementField_FK { get; set; }
    }
}
