//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLDYE_BIFInTransit
    {
        public int BIFT_Pk { get; set; }
        public bool BIFT_PickingList { get; set; }
        public System.DateTime BIFT_PickingList_Date { get; set; }
        public int BIFT_PickingList_Number { get; set; }
        public bool BIFT_Despatched { get; set; }
        public Nullable<System.DateTime> BIFT_Despatched_Date { get; set; }
        public int BIFT_Despatch_FK { get; set; }
        public bool BIFT_Receipted { get; set; }
        public Nullable<System.DateTime> BIFT_Receipt_Date { get; set; }
        public int BIFT_FromFabric_FK { get; set; }
        public int BIFT_ToFabric_FK { get; set; }
        public int BIFT_Delivery_Number { get; set; }
    }
}
