//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLKNI_YarnOrderPallets
    {
        public int TLKNIOP_Pk { get; set; }
        public int TLKNIOP_PalletNo { get; set; }
        public string TLKNIOP_TLPalletNo { get; set; }
        public string TLKNIOP_Grade { get; set; }
        public int TLKNIOP_YarnType_FK { get; set; }
        public int TLKNIOP_Cones { get; set; }
        public decimal TLKNIOP_GrossWeight { get; set; }
        public decimal TLKNIOP_TareWeight { get; set; }
        public decimal TLKNIOP_NettWeight { get; set; }
        public int TLKNIOP_ConesReserved { get; set; }
        public decimal TLKNIOP_NettWeightReserved { get; set; }
        public Nullable<int> TLKNIOP_YarnOrder_FK { get; set; }
        public int TLKNIOP_Store_FK { get; set; }
        public Nullable<int> TLKNIOP_HeaderRecord_FK { get; set; }
        public Nullable<System.DateTime> TLKNIOP_DatePacked { get; set; }
        public bool TLKNIOP_CommisionCust { get; set; }
        public bool TLKNIOP_OwnYarn { get; set; }
        public int TLKNIOP_ReservedBy { get; set; }
        public bool TLKNIOP_OrderConfirmed { get; set; }
        public Nullable<System.DateTime> TLKNIOP_ReservedDate { get; set; }
        public bool TLKNIOP_SplitPallet { get; set; }
        public int TLKNIOP_ConesReturned { get; set; }
        public decimal TLKNIOP_NettWeightReturned { get; set; }
        public bool TLKNIOP_PalletAllocated { get; set; }
        public int TLKNIOP_CommissionCustomer_FK { get; set; }
        public decimal TLKNIOP_NettWeightConsummed { get; set; }
        public decimal TLKNIOP_AdditionalYarn { get; set; }
    }
}
