//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLSPN_YarnOrder
    {
        public int YarnO_Pk { get; set; }
        public System.DateTime YarnO_Date { get; set; }
        public System.DateTime YarnO_DelDate { get; set; }
        public int YarnO_OrderNumber { get; set; }
        public int Yarno_LayDown_FK { get; set; }
        public int Yarno_CottonOrigin_FK { get; set; }
        public int YarnO_Supplier_FK { get; set; }
        public int Yarno_YarnType_FK { get; set; }
        public int Yarno_MachNo_FK { get; set; }
        public int Yarno_OrderWeight { get; set; }
        public string Yarno_Packing { get; set; }
        public bool Yarno_Closed { get; set; }
        public Nullable<System.DateTime> Yarno_ClosedDate { get; set; }
        public int YarnO_TransactionType_FK { get; set; }
        public bool YarnO_Reinstate { get; set; }
        public Nullable<int> YarnO_MergeContract_FK { get; set; }
    }
}
