//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTI2_WF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTI2Entities1 : DbContext
    {
        public TTI2Entities1()
            : base("name=TTI2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TLADM_AuxColours> TLADM_AuxColours { get; set; }
        public virtual DbSet<TLADM_Colours> TLADM_Colours { get; set; }
        public virtual DbSet<TLADM_ConsumableGroups> TLADM_ConsumableGroups { get; set; }
        public virtual DbSet<TLADM_ConsumablesDC> TLADM_ConsumablesDC { get; set; }
        public virtual DbSet<TLADM_ConsumablesOther> TLADM_ConsumablesOther { get; set; }
        public virtual DbSet<TLADM_Cotton> TLADM_Cotton { get; set; }
        public virtual DbSet<TLADM_CottonOrigin> TLADM_CottonOrigin { get; set; }
        public virtual DbSet<TLADM_CustomerFile> TLADM_CustomerFile { get; set; }
        public virtual DbSet<TLADM_CustomerTypes> TLADM_CustomerTypes { get; set; }
        public virtual DbSet<TLADM_Departments> TLADM_Departments { get; set; }
        public virtual DbSet<TLADM_FabricProduct> TLADM_FabricProduct { get; set; }
        public virtual DbSet<TLADM_FabricType> TLADM_FabricType { get; set; }
        public virtual DbSet<TLADM_FabricWeight> TLADM_FabricWeight { get; set; }
        public virtual DbSet<TLADM_FabWidth> TLADM_FabWidth { get; set; }
        public virtual DbSet<TLADM_FinishedGoods> TLADM_FinishedGoods { get; set; }
        public virtual DbSet<TLADM_GarmentDef> TLADM_GarmentDef { get; set; }
        public virtual DbSet<TLADM_GarmentDefectCodes> TLADM_GarmentDefectCodes { get; set; }
        public virtual DbSet<TLADM_Griege> TLADM_Griege { get; set; }
        public virtual DbSet<TLADM_Labels> TLADM_Labels { get; set; }
        public virtual DbSet<TLADM_MachineDefinitions> TLADM_MachineDefinitions { get; set; }
        public virtual DbSet<TLADM_MachineMaintenance> TLADM_MachineMaintenance { get; set; }
        public virtual DbSet<TLADM_MachineOperators> TLADM_MachineOperators { get; set; }
        public virtual DbSet<TLADM_NonStockCat> TLADM_NonStockCat { get; set; }
        public virtual DbSet<TLADM_NonStockItems> TLADM_NonStockItems { get; set; }
        public virtual DbSet<TLADM_ProductRating> TLADM_ProductRating { get; set; }
        public virtual DbSet<TLADM_ProductRating_Detail> TLADM_ProductRating_Detail { get; set; }
        public virtual DbSet<TLADM_ProductTypes> TLADM_ProductTypes { get; set; }
        public virtual DbSet<TLADM_QualityDefinition> TLADM_QualityDefinition { get; set; }
        public virtual DbSet<TLADM_RejectReasons> TLADM_RejectReasons { get; set; }
        public virtual DbSet<TLADM_Ribbing> TLADM_Ribbing { get; set; }
        public virtual DbSet<TLADM_Sizes> TLADM_Sizes { get; set; }
        public virtual DbSet<TLADM_StockTakeFreq> TLADM_StockTakeFreq { get; set; }
        public virtual DbSet<TLADM_StockTypes> TLADM_StockTypes { get; set; }
        public virtual DbSet<TLADM_StoreTypes> TLADM_StoreTypes { get; set; }
        public virtual DbSet<TLADM_Styles> TLADM_Styles { get; set; }
        public virtual DbSet<TLADM_Suppliers> TLADM_Suppliers { get; set; }
        public virtual DbSet<TLADM_Trims> TLADM_Trims { get; set; }
        public virtual DbSet<TLADM_UOM> TLADM_UOM { get; set; }
        public virtual DbSet<TLADM_WhseStore> TLADM_WhseStore { get; set; }
        public virtual DbSet<TLADM_Yarn> TLADM_Yarn { get; set; }
        public virtual DbSet<TLCMT_ProductDefects> TLCMT_ProductDefects { get; set; }
    }
}
